### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by Talasl1** [nosyn00b/GOG2_Fanatical_Plugin#1]
Sorry to write here, but I would love to install your plugin to my galaxy, but I honestly have no idea how, I have tried the slashbunny plugin you write, but somehow I can not fathom how to make it to include your plugin, I would appreciate any help you can give an old noob like me ;)

With kind regards,
Thomas

**Comment by nosyn00b** [comment]
Hi Talasl1,
     sorry for not aswering before, quite busy this days :-)

I wrote a very detailed installation procedure in the Overview. Slashbunny method is perhaps more easy if you already used that for downloading and setting up other plugins: I personally recommend the "Downloading the last release" way for all the others :). 

Please be more specific on what is not clear for you, I'll try to help.

NN
