### ISSUE TITLE
Impossible to Connect

### ISSUE THREAD

**Issue by milroneth** [nosyn00b/GOG2_Fanatical_Plugin#3]
This issue is already fixed. I cannot believe how much time I spent on this, but can you PLEASE accept #2 that updates the manifest to declare version `0.0.2`? I used Slashbunny's plugin downloader, which downloads the old version but never realised that was the problem as I had checked the manifests and they where the same...

Original issue follows:
__________________________

I was unable to get the plugin to Connect, no matter what I tried.

The browser window for Fanatical appears, however the plugin does not seem to be able to interact with it at all. The login prompt never comes up, even with `LAZYDOM_MODE` enabled. For testing, I tried `CLOSE_COOKIEPOLICYCONSENT`, doesn't work either.

I thought that doing the needed process manually might do the trick, but even if I login myself and proceed to the orders page (as per the `END_URI_REGEX` value), it never closes the window, I have to close it manually, which aborts the process leaving the plugin disconnected.

Same with visiting the bundles page with `NOAUTH_DEBUGMODE` enabled. There is no way to make it realize it's all done and it should proceed.

GOG Galaxy version: 2.0.45.61 - Beta
Fresh installation, never tried before so I don't know when it stopped working.
Every other plugin I used (I installed a dozen) worked properly.

**EDIT:** I'm not sure this will be helpful, but I'm attaching a log file with a single failed attempt, manual login and browser window exit, with the default configuration:
[plugin-fanatical-f72d61b1-f2e2-4e46-98e0-c5f33cca34b8.log](https://github.com/nosyn00b/GOG2_Fanatical_Plugin/files/7799867/plugin-fanatical-f72d61b1-f2e2-4e46-98e0-c5f33cca34b8.log)

**Comment by nosyn00b** [comment]
Sorry to hear you spent much time on this!

**Comment by nosyn00b** [comment]
Release Fixed. Thanks for pointing this out.
